// AUTOGENERATED FILE; see /go/src/github.com/docker/docker/hack/make/.go-autogen
package dockerversion

var (
	GITCOMMIT string = "c8dc729"
	VERSION   string = "1.9.0-dev"
	BUILDTIME string = "Thu Sep 10 16:52:04 UTC 2015"

	IAMSTATIC string = "true"
	INITSHA1  string = "cdcab3710079794053d5ca4e1062980c4b730c6e"
	INITPATH  string = ""
)
