#!/bin/bash

#docker-record
#
#Usage:
#    docker-record <CONTAINER>
#    docker-record <CONTAINER> --replay

CONTAINER=$1
REPLAY=$2

if [ -z $REPLAY ]
then
	./session.sh $CONTAINER
else
	docker cp $CONTAINER:/tmp/record sessions/$CONTAINER
	./replay $CONTAINER
fi
	
