name: celery-build-test-flow
description: Workflow for building and testing celery pypi
volumes:
    - ~/workspace:/workspace
    - ~/builds:/builds
jobs:
    - build-celery-sdist:
        image: python:2.7
        working_dir: /workspace
        steps:
           - set -x
           - cd /workspace
           - rm -rf /workspace/*
           - git clone https://github.com/celery/celery
           - cd celery
           - python setup.py sdist
           - cp /workspace/celery/dist/* /builds
        output: /builds/celery-*.tar.gz
